In [1]:
import numpy as np

In [2]:
# 50
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])


/home/ali/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [3]:
array_of_arrays.flatten()

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [5]:
array_of_arrays.ravel()

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [6]:
array_of_arrays.reshape(-1)

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [7]:
[a for arr in array_of_arrays for a in arr]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
np.concatenate(array_of_arrays)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 51
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

array([2, 3, 2, 2, 2, 1])

In [15]:
np.eye(4)[arr][:, 1:]

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [16]:
# 52
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [21]:
# 54
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)

[ 9  4 15  0 17 16 17  8  9  0]


In [18]:
a.argsort()

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6])

In [22]:
a.argsort().argsort()

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

In [20]:
a

array([ 0,  0,  4,  8,  9,  9, 15, 16, 17, 17])

In [23]:
list(zip(a.argsort().argsort(), a))

[(4, 9),
 (2, 4),
 (6, 15),
 (0, 0),
 (8, 17),
 (7, 16),
 (9, 17),
 (3, 8),
 (5, 9),
 (1, 0)]

In [24]:
np.unique(a)

array([ 0,  4,  8,  9, 15, 16, 17])

In [25]:
np.unique(a).argsort()

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
b = np.unique(a)
temp = b[3]
b[3] = b[5]
b[5] = temp
b

array([ 0,  4,  8, 16, 15,  9, 17])

In [28]:
b.argsort()

array([0, 1, 2, 5, 4, 3, 6])

In [29]:
# 55
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [30]:
a.argsort()

array([[3, 1, 0, 2, 4],
       [4, 2, 3, 0, 1]])

In [31]:
a.argsort().argsort()

array([[2, 1, 3, 0, 4],
       [3, 4, 1, 2, 0]])

In [32]:
a.argsort().argsort().argsort()

array([[3, 1, 0, 2, 4],
       [4, 2, 3, 0, 1]])

In [33]:
a.argsort(axis=None)

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6])

In [34]:
a.flatten()

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [35]:
# 56
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [36]:
np.max(a, axis=1)

array([9, 8, 6, 3, 9])