In [1]:
import numpy as np

In [2]:
# 59
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [3]:
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

In [5]:
iris[:, :-1] = iris[:, :-1].astype(float) 
iris[:, -1] = iris[:, -1].astype(str)

In [7]:
setosa = iris[iris[:, -1] == 'Iris-setosa']
versicolor = iris[iris[:, -1] == 'Iris-versicolor']
virginica = iris[iris[:, -1] == 'Iris-virginica']
setosa[:5, :]

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa']], dtype=object)

In [8]:
np.mean(setosa[:, :-1], axis=0)

array([5.005999999999999, 3.4180000000000006, 1.464, 0.2439999999999999],
      dtype=object)

In [9]:
np.mean(versicolor[:, :-1], axis=0)

array([5.936, 2.7700000000000005, 4.26, 1.3259999999999998], dtype=object)

In [10]:
np.mean(virginica[:, :-1], axis=0)

array([6.587999999999998, 2.9739999999999998, 5.552, 2.026], dtype=object)

In [11]:
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
pil = np.genfromtxt(URL)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [13]:
# 61
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
arr[~np.isnan(arr)]

array([1., 2., 3., 5., 6., 7.])

In [14]:
# 62
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
np.sqrt(np.sum((a - b) ** 2))

6.708203932499369

In [15]:
np.linalg.norm(a - b)

6.708203932499369

In [17]:
# 63
from scipy.signal import find_peaks

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
find_peaks(a)[0]

array([2, 5])

In [20]:
np.diff(np.sign(np.diff(a)))

array([ 0, -2,  2,  0, -2,  2])

In [26]:
# 64
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1, 2, 3])

In [27]:
a_2d - b_1d.reshape(3, 1)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [35]:
# 65
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.where((np.cumsum(x == 1)) == 5)[0].min()

8

In [33]:
x==1

array([ True, False,  True,  True, False, False, False,  True,  True,
       False,  True,  True, False])

In [36]:
[i for i, v in enumerate(x) if v == 1][4]

8

In [38]:
np.where(x == 1)[0][4]

8

In [39]:
# 66
dt64 = np.datetime64('2018-02-25 22:10:10')

In [40]:
dt64


numpy.datetime64('2018-02-25T22:10:10')

In [41]:
dt64.tolist()

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [42]:
from datetime import datetime

dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [43]:
# 67
np.random.seed(100)
Z = np.random.randint(10, size=10)
Z

array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

In [44]:
np.cumsum(Z) / 3

array([ 2.66666667,  5.33333333,  6.33333333,  8.66666667, 11.        ,
       11.        , 12.33333333, 13.        , 14.66666667, 15.33333333])

In [46]:
# 68
def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(5, 10, 3)
#> array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [47]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


In [48]:
np.arange(dates[0], dates[-1])

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22'], dtype='datetime64[D]')

In [49]:
# 70

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
