In [1]:
import numpy as np

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [3]:
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

### exercise 44

In [13]:
# 44
iris = np.hstack([iris[:, :4].astype(float), iris[:, -1].astype(str).reshape(iris.shape[0], 1)])
iris

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [15]:
sorted_iris = iris[iris[:, 0].argsort()]
sorted_iris

array([['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['4.4', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.4', '3.0', '1.3', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.5', '2.3', '1.3', '0.3', 'Iris-setosa'],
       ['4.6', '3.6', '1.0', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['4.6', '3.2', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.3', 'Iris-setosa'],
       ['4.8', '3.4', '1.9', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.1', '1.6', '0.2', 'Iris-setosa'],
       ['4.9', '2.4', '3.3', '1.0', 'Iris-versicolor'],
       ['4.9', '2.5', '4.5', '1.7', 'Iris-virginica'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
     

## exercise 45

In [20]:
# most frequent value of 3rd column
import scipy.stats as st
st.mode(iris[:, 2]).mode[0]

'1.5'

## exercise 46

In [21]:
# Q. Find the position of the first occurrence of a value greater than 1.0 
# in petalwidth 4th column of iris dataset.
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50])

## exercise 47

In [22]:
# Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a[a < 10] = 10
a[a > 30] = 30

## exercise 48

In [23]:
# Q. Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.argsort(a)[-5:]

array([18,  7,  3, 10, 15])

## exercise 49

In [26]:
# Q. Compute the counts of unique values row-wise.
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
np.unique(arr, axis=1, return_counts=True)

(array([[ 1,  3,  3,  4,  5,  6,  8,  8,  9,  9],
        [ 5,  3, 10,  2,  1,  7,  1,  9,  3,  3],
        [ 5,  2,  8,  6,  4,  2,  4,  5,  2,  5],
        [10,  9,  3,  1,  4,  6,  3, 10,  8,  8],
        [ 1,  2,  3,  8,  9,  6,  7,  3,  1,  2],
        [ 9, 10,  6,  6,  4,  1,  5,  3,  2,  9]]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

## exercise 50

In [27]:
# Q. Convert array_of_arrays into a flat linear 1d array.

arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

/home/ali/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [31]:
np.hstack(array_of_arrays)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])